version: '3'

services:
  api:
    image: wns1601/registration-api:1.1.1
    container_name: registration-api
    volumes:
      - ./databases:/opt/app/databases
    ports:
      - 3000:3000
    restart: always
  client:
    image: wns1601/registration-client:3.0
    container_name: registration-client
    ports: 
      - 8080:80
    depends_on: 
      - api
    restart: always
