version: '3'

services:
  api:
    image: wns1601/registration-api:1.1
    container_name: registration-api
    volumes:
      - ./databases:/opt/app/databases
    ports:
      - 3000:3000
    restart: always
